### ISSUE TITLE
[BUG] `normalize` will report a missing scripts as invalid, then delete it instead of creating it

### ISSUE THREAD

**Issue by legodude17** [npm/package-json#81] opened 2024-01-19 22:14 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the `scripts` key is entirely missing from a `package.json`, the `normalize` function will report it as invalid and that it was removed, then delete. Of course, the key never existed at all, so deleting it does nothing.

See:
npm/cli#7127

### Expected Behavior

If `scripts` being required to be at least an empty object is intended, then I'd expect `normalize` to set it to that instead of deleting it. If `scripts` can be omitted, then I'd expect it to not report them as invalid.

As an aside, the message `Removed invalid "scripts"` is very misleading if `scripts` was already missing.

### Steps To Reproduce

1. `npm init -y`
2. `npm pkg delete scripts`
3. `npm i @npmcli/package-json`
4. Put this as `index.js`:
```js
const changes = [];
require("@npmcli/package-json")
  .fix(".", { changes })
  .then(
    (res) => console.log(changes.join("\n"), res.content.scripts),
    console.error
  );
```
5. `node index.js`
6. Prints `Removed invalid "scripts" undefined`, it errored about the missing scripts, but didn't fix it.

### Environment

- npm: 10.3.0
- Node: 21.9.0
- OS: macOS 13.6.3
- platform: Macbook Pro

**Comment by wraithgar** [comment] 2024-01-22 16:05
This is duplicate of https://github.com/npm/cli/issues/7127, we don't need to track this twice.

**Closed by wraithgar** 2024-01-22 16:05 UTC
